// Sidebar labels sit under a framework and category group, so they name the
// subject of the rule instead of repeating the imperative page title.
export const RULE_NAVIGATION_TITLE_MAX_LENGTH = 20;

export const ruleNavigationTitles: Record<string, string> = {
  "docus/appconfig/no-unknown-key": "Unknown keys",
  "docus/layers/no-empty-app-vue-shadow": "Empty app.vue",

  "nitro/context/no-navigateto-in-nitro": "navigateTo",
  "nitro/context/no-usenuxtapp-in-nitro": "useNuxtApp",
  "nitro/h3/no-http-error-masking": "HTTP error masking",
  "nitro/h3/no-removed-send": "Removed send()",
  "nitro/h3/prefer-redirect-response": "Redirect responses",
  "nitro/h3/prefer-with-base": "withBase",
  "nitro/migration/no-v2-imports": "Nitro 2 imports",
  "nitro/request/prefer-assert-method": "assertMethod",
  "nitro/request/prefer-get-request-ip": "Request IP utilities",
  "nitro/request/prefer-route-method-suffix": "Method suffixes",
  "nitro/request/prefer-validated-body": "Validated body",
  "nitro/request/prefer-validated-query": "Validated query",
  "nitro/request/prefer-validated-router-params": "Validated params",
  "nitro/runtime/no-event-runtime-config-in-server": "Drop event (Nitro 3)",
  "nitro/runtime/require-event-runtime-config-in-server": "Pass the event",
  "nitro/server/no-browser-api": "Browser APIs",
  "nitro/server/no-client-composables": "App composables",

  "nuxt-better-auth/require-standard-auth-handler-mount": "Better Auth handler",
  "nuxt-content/links/no-broken-internal-to-link": "Broken links",
  "nuxt-content/no-querycontent-legacy-api": "queryCollection",
  "nuxt-image/prefer-nuxtimg": "NuxtImg",
  "nuxt-image/prefer-nuxtpicture-for-formats": "NuxtPicture",
  "nuxt-image/prefer-responsive-dimensions": "Image dimensions",
  "nuxt-image/require-alt": "Image alt text",
  "nuxt-scripts/no-raw-third-party-script-tag": "Raw script tags",
  "nuxt-scripts/no-third-party-config-script": "app.head scripts",
  "nuxt-scripts/no-third-party-usehead-script": "useHead scripts",
  "nuxt-ui/prefer-u-button": "UButton",
  "nuxt-ui/prefer-u-form-controls": "Form controls",
  "nuxt-ui/require-uapp-root": "UApp root",
  "nuxt/async-data-explicit-key-for-refreshable": "Refresh keys",
  "nuxt/async-data-handler-pure": "Pure handlers",
  "nuxt/async-data-no-mutation-methods": "Mutating async data",
  "nuxt/composables/export-name-matches-file": "Export names",
  "nuxt/composables/no-nested-autoimport-assumption": "Composable subdirs",
  "nuxt/config/no-ignored-compatibility-config": "Ignored config",
  "nuxt/context/no-composable-after-await": "Calls after await",
  "nuxt/context/no-legacy-process-client-server": "import.meta flags",
  "nuxt/fetch/create-usefetch-must-be-exported-in-scanned-dir": "Factory directories",
  "nuxt/fetch/forward-auth-headers-ssr": "SSR auth headers",
  "nuxt/fetch/keyed-composable-registration-required": "Keyed composables",
  "nuxt/fetch/no-await-inside-custom-wrapper": "Await in wrappers",
  "nuxt/fetch/no-raw-fetch-in-setup": "Raw fetch in setup",
  "nuxt/fetch/prefer-create-use-fetch": "Data factories",
  "nuxt/fetch/require-stable-asyncdata-key": "Stable data keys",
  "nuxt/hydration/no-browser-global-in-universal-code": "Browser globals",
  "nuxt/hydration/no-browser-side-effects-in-setup": "Setup side effects",
  "nuxt/hydration/no-client-conditional-in-template": "Client conditionals",
  "nuxt/hydration/no-time-dependent-render-without-nuxttime-or-clientonly": "Time-based render",
  "nuxt/hydration/prefer-usecookie-for-initial-client-state": "useCookie state",
  "nuxt/imports/no-auto-import-collision": "Name collisions",
  "nuxt/imports/no-conflicting-usefetch-import": "Shadowed useFetch",
  "nuxt/imports/no-explicit-auto-import": "Redundant imports",
  "nuxt/middleware/no-route-middleware-api-security": "Middleware for APIs",
  "nuxt/module/explicit-runtime-imports": "Runtime imports",
  "nuxt/module/require-meta": "Module meta",
  "nuxt/module/resolve-runtime-paths": "Runtime paths",
  "nuxt/no-global-refresh-without-justification": "Global refresh",
  "nuxt/no-manual-action-usefetch": "immediate: false",
  "nuxt/no-mutation-toast-in-usefetch-callback": "Fetch callbacks",
  "nuxt/plugins/no-subdir-auto-registration-assumption": "Nested plugins",
  "nuxt/post-fetch-requires-readonly-marker": "POST as async data",
  "nuxt/preview-mode-global-refresh": "Preview refresh",
  "nuxt/project/prefer-app-directory-placement": "app/ directories",
  "nuxt/review/api-authorization-coverage": "API authorization",
  "nuxt/routing/no-hash-sensitive-route-fullpath-in-ssr-markup": "route.fullPath",
  "nuxt/routing/no-route-object-page-key": "Route page keys",
  "nuxt/routing/no-router-navigation-in-setup": "Navigation in setup",
  "nuxt/routing/no-useroute-in-middleware": "to/from arguments",
  "nuxt/routing/prefer-nuxt-useroute": "Nuxt useRoute",
  "nuxt/routing/prefer-nuxtlink": "NuxtLink",
  "nuxt/routing/prefer-nuxtpage-over-routerview": "NuxtPage",
  "nuxt/routing/return-navigateto-in-middleware": "Return navigateTo",
  "nuxt/runtime/no-plain-env-in-app-code": "process.env in app",
  "nuxt/runtime/no-secret-in-public-config": "Public secrets",
  "nuxt/security/no-unsafe-usehead-script": "Unsafe scripts",
  "nuxt/security/prefer-useheadsafe-for-untrusted-values": "useHeadSafe",
  "nuxt/seo/prefer-seo-composables": "SEO composables",
  "nuxt/shared/no-nested-shared-autoimport-assumption": "Nested shared/ files",
  "nuxt/shared/no-vue-or-nitro-context-in-shared": "Shared code context",
  "nuxt/structure/no-composable-in-utils": "utils/ composables",
  "nuxt/structure/no-stateless-composable": "Plain use* helpers",
  "nuxt/state/no-nonserializable-usestate": "useState values",
  "nuxt/state/prefer-explicit-usestate-key-in-exported-composables": "useState keys",
  "nuxthub/no-personalized-cached-handler": "Per-user caching",
  "nuxthub/prefer-cached-event-handler": "Cached handlers",
  "vueuse/no-nuxt-auto-import-collision": "VueUse collisions",
  "vueuse/prefer-use-observers": "Observers",
  "vueuse/prefer-use-scroll-and-element": "Scroll & element",
  "vueuse/prefer-use-storage": "Storage",
  "vueuse/prefer-use-timers": "Timers",
  "vueuse/prefer-usebreakpoints": "useBreakpoints",
  "vueuse/prefer-useclipboard": "useClipboard",
  "vueuse/prefer-useevent-listener": "useEventListener",
  "vueuse/prefer-usewindow-size": "useWindowSize",

  "package/no-phantom-dependencies": "Phantom deps",
  "package/no-required-optional-peer": "Optional peers",

  "shadcn/no-arbitrary-values": "Arbitrary values",
  "shadcn/no-inline-styles": "Inline styles",
  "shadcn/no-raw-colors": "Color tokens",
  "shadcn/no-restyle": "Component restyling",
  "shadcn/no-unknown-classes": "Unknown classes",
  "shadcn/require-static-classes": "Static classes",

  "typescript/boundaries/no-unvalidated-deserialization": "Deserialized values",
  "typescript/evidence/no-caller-chosen-result-type": "Caller-chosen types",
  "typescript/evidence/no-chained-type-assertions": "Chained assertions",
  "typescript/evidence/no-known-value-widening": "Value widening",
  "typescript/evidence/no-object-parameters": "object parameters",
  "typescript/evidence/no-unknown-type-aliases": "unknown aliases",
  "typescript/evidence/no-widen-then-assert": "Widen then assert",
  "typescript/performance/no-array-filter-map": "filter().map()",
  "typescript/performance/no-reduce-accumulator-copy": "Reducer copies",
  "typescript/strict/no-runtime-typeof": "Runtime typeof",
  "typescript/strict/require-safety-comment-for-type-assertion": "Assertion notes",
  "typescript/style/no-conditional-empty-object-spread": "Conditional spreads",

  "vite/assets/no-dynamic-new-url": "Dynamic new URL",
  "vite/assets/no-public-src-import": "Public asset imports",
  "vite/assets/no-src-absolute-public-url": "Source public URLs",
  "vite/define/no-runtime-object-define": "Object defines",
  "vite/define/no-secret-define": "Secrets in define",
  "vite/define/no-untyped-define": "Typed define",
  "vite/define/no-unused-define": "Unused define",
  "vite/env/no-broad-env-prefix": "Broad env prefixes",
  "vite/env/no-client-secret-pattern": "Client secret env",
  "vite/env/no-empty-env-prefix": "Empty env prefix",
  "vite/env/no-untyped-env": "Typed env",
  "vite/env/prefer-direct-import-meta-env-access": "import.meta.env",
  "vite/hmr/require-dispose-for-side-effects": "HMR dispose",
  "vite/imports/no-barrel-files": "Barrel files",
  "vite/imports/require-static-glob-pattern": "Static glob patterns",
  "vite/plugin/prefer-transform-filter": "Transform filters",
  "vite/plugin/require-name": "Plugin names",
  "vite/server/no-broad-fs-allow": "server.fs.allow",
  "vite/server/no-disabled-fs-strict": "server.fs.strict",
  "vite/ssr/no-browser-global-in-ssr-entry": "Browser globals",
  "vite/worker/no-dynamic-worker-url": "Dynamic workers",
  "vite/worker/no-node-api-in-worker": "Node APIs",
  "vite/worker/require-worker-url-pattern": "Worker URL pattern",

  "vue/i18n/no-untranslated-text": "Untranslated text",
  "vue/i18n/no-unused-translations": "Unused translations",
  "vue/lifecycle/no-mutation-in-onupdated": "onUpdated writes",
  "vue/lifecycle/prefer-use-event-listener": "useEventListener",
  "vue/lifecycle/require-cleanup": "Lifecycle cleanup",
  "vue/reactivity/defineprops-watch-getter": "Prop watch getters",
  "vue/reactivity/no-ref-as-operand": "Refs as operands",
  "vue/reactivity/no-setup-props-destructure": "Props destructuring",
  "vue/reactivity/prefer-composable-ref-return": "Composable refs",
  "vue/security/restrict-v-html": "v-html",
  "vue/ssr/data-allow-mismatch-surgical": "allow-mismatch",
  "vue/ssr/no-browser-api-in-setup": "Browser APIs",
  "vue/ssr/no-random-or-local-time-render": "Random & time",
  "vue/ssr/use-id-for-stable-ids": "useId",
  "vue/style/prefer-define-model": "defineModel",
  "vue/style/prefer-props-destructure-defaults": "Props defaults",
  "vue/style/prefer-type-props": "Type-based props",
  "vue/template/html-button-has-type": "Button type",
  "vue/template/prefer-same-name-prop-shorthand": "Prop shorthand",
  "vue/template/prefer-true-attribute-shorthand": "Boolean shorthand",
  "vue/template/prefer-use-template-ref": "useTemplateRef",
  "vue/watch/no-async-watcheffect-after-await-read": "Reads after await",
  "vue/watch/no-onwatchercleanup-after-await": "onWatcherCleanup",
  "vue/watch/require-post-flush-for-dom-read": "DOM reads",
  "vue/watch/require-side-effect-cleanup": "Watcher cleanup",
};
