import { defineDoctorDiagnostics } from "../../core/src/diagnostics.js";

export const nuxtDiagnosticRegistry = defineDoctorDiagnostics([
  { code: "NUXT0001", ruleId: "docus/appconfig/no-unknown-key" },
  { code: "NUXT0002", ruleId: "docus/layers/no-empty-app-vue-shadow" },
  { code: "NUXT0003", ruleId: "nuxt-better-auth/require-standard-auth-handler-mount" },
  { code: "NUXT0004", ruleId: "nuxt-content/links/no-broken-internal-to-link" },
  { code: "NUXT0005", ruleId: "nuxt-content/no-querycontent-legacy-api" },
  { code: "NUXT0006", ruleId: "nuxt-image/prefer-nuxtimg" },
  { code: "NUXT0007", ruleId: "nuxt-image/prefer-nuxtpicture-for-formats" },
  { code: "NUXT0008", ruleId: "nuxt-image/prefer-responsive-dimensions" },
  { code: "NUXT0009", ruleId: "nuxt-image/require-alt" },
  { code: "NUXT0010", ruleId: "nuxt-scripts/no-raw-third-party-script-tag" },
  { code: "NUXT0011", ruleId: "nuxt-scripts/no-third-party-config-script" },
  { code: "NUXT0012", ruleId: "nuxt-scripts/no-third-party-usehead-script" },
  { code: "NUXT0013", ruleId: "nuxt-ui/prefer-u-button" },
  { code: "NUXT0014", ruleId: "nuxt-ui/prefer-u-form-controls" },
  { code: "NUXT0015", ruleId: "nuxt-ui/require-uapp-root" },
  { code: "NUXT0016", ruleId: "nuxt/async-data-explicit-key-for-refreshable" },
  { code: "NUXT0017", ruleId: "nuxt/async-data-handler-pure" },
  { code: "NUXT0018", ruleId: "nuxt/async-data-no-mutation-methods" },
  { code: "NUXT0019", ruleId: "nuxt/composables/no-nested-autoimport-assumption" },
  { code: "NUXT0020", ruleId: "nuxt/context/no-composable-after-await" },
  { code: "NUXT0021", ruleId: "nuxt/context/no-legacy-process-client-server" },
  { code: "NUXT0022", ruleId: "nuxt/fetch/create-usefetch-must-be-exported-in-scanned-dir" },
  { code: "NUXT0023", ruleId: "nuxt/fetch/forward-auth-headers-ssr" },
  { code: "NUXT0024", ruleId: "nuxt/fetch/keyed-composable-registration-required" },
  { code: "NUXT0025", ruleId: "nuxt/fetch/no-await-inside-custom-wrapper" },
  { code: "NUXT0026", ruleId: "nuxt/fetch/no-raw-fetch-in-setup" },
  { code: "NUXT0027", ruleId: "nuxt/fetch/prefer-create-use-fetch" },
  { code: "NUXT0028", ruleId: "nuxt/fetch/require-stable-asyncdata-key" },
  { code: "NUXT0029", ruleId: "nuxt/hydration/no-browser-global-in-universal-code" },
  { code: "NUXT0030", ruleId: "nuxt/hydration/no-browser-side-effects-in-setup" },
  { code: "NUXT0031", ruleId: "nuxt/hydration/no-client-conditional-in-template" },
  {
    code: "NUXT0032",
    ruleId: "nuxt/hydration/no-time-dependent-render-without-nuxttime-or-clientonly",
  },
  { code: "NUXT0033", ruleId: "nuxt/hydration/prefer-usecookie-for-initial-client-state" },
  { code: "NUXT0034", ruleId: "nuxt/imports/no-auto-import-collision" },
  { code: "NUXT0035", ruleId: "nuxt/imports/no-conflicting-usefetch-import" },
  { code: "NUXT0036", ruleId: "nuxt/imports/no-explicit-auto-import" },
  { code: "NUXT0037", ruleId: "nuxt/middleware/no-route-middleware-api-security" },
  { code: "NUXT0038", ruleId: "nuxt/no-global-refresh-without-justification" },
  { code: "NUXT0039", ruleId: "nuxt/no-manual-action-usefetch" },
  { code: "NUXT0040", ruleId: "nuxt/no-mutation-toast-in-usefetch-callback" },
  { code: "NUXT0041", ruleId: "nuxt/plugins/no-subdir-auto-registration-assumption" },
  { code: "NUXT0042", ruleId: "nuxt/post-fetch-requires-readonly-marker" },
  { code: "NUXT0043", ruleId: "nuxt/preview-mode-global-refresh" },
  { code: "NUXT0044", ruleId: "nuxt/project/prefer-app-directory-placement" },
  { code: "NUXT0045", ruleId: "nuxt/routing/no-hash-sensitive-route-fullpath-in-ssr-markup" },
  { code: "NUXT0046", ruleId: "nuxt/routing/no-route-object-page-key" },
  { code: "NUXT0047", ruleId: "nuxt/routing/no-router-navigation-in-setup" },
  { code: "NUXT0048", ruleId: "nuxt/routing/no-useroute-in-middleware" },
  { code: "NUXT0049", ruleId: "nuxt/routing/prefer-nuxt-useroute" },
  { code: "NUXT0050", ruleId: "nuxt/routing/prefer-nuxtlink" },
  { code: "NUXT0051", ruleId: "nuxt/routing/prefer-nuxtpage-over-routerview" },
  { code: "NUXT0052", ruleId: "nuxt/routing/return-navigateto-in-middleware" },
  { code: "NUXT0053", ruleId: "nuxt/runtime/no-plain-env-in-app-code" },
  { code: "NUXT0054", ruleId: "nuxt/runtime/no-secret-in-public-config" },
  { code: "NUXT0055", ruleId: "nuxt/security/no-unsafe-usehead-script" },
  { code: "NUXT0056", ruleId: "nuxt/security/prefer-useheadsafe-for-untrusted-values" },
  { code: "NUXT0057", ruleId: "nuxt/seo/prefer-seo-composables" },
  { code: "NUXT0058", ruleId: "nuxt/shared/no-nested-shared-autoimport-assumption" },
  { code: "NUXT0059", ruleId: "nuxt/shared/no-vue-or-nitro-context-in-shared" },
  { code: "NUXT0060", ruleId: "nuxt/state/no-nonserializable-usestate" },
  { code: "NUXT0061", ruleId: "nuxt/state/prefer-explicit-usestate-key-in-exported-composables" },
  { code: "NUXT0062", ruleId: "nuxthub/no-personalized-cached-handler" },
  { code: "NUXT0063", ruleId: "nuxthub/prefer-cached-event-handler" },
  { code: "NUXT0064", ruleId: "vueuse/no-nuxt-auto-import-collision" },
  { code: "NUXT0065", ruleId: "vueuse/prefer-use-observers" },
  { code: "NUXT0066", ruleId: "vueuse/prefer-use-scroll-and-element" },
  { code: "NUXT0067", ruleId: "vueuse/prefer-use-storage" },
  { code: "NUXT0068", ruleId: "vueuse/prefer-use-timers" },
  { code: "NUXT0069", ruleId: "vueuse/prefer-usebreakpoints" },
  { code: "NUXT0070", ruleId: "vueuse/prefer-useclipboard" },
  { code: "NUXT0071", ruleId: "vueuse/prefer-useevent-listener" },
  { code: "NUXT0072", ruleId: "vueuse/prefer-usewindow-size" },
]);

export const diagnostics = nuxtDiagnosticRegistry.diagnostics;
export const diagnosticCodesByRuleId = nuxtDiagnosticRegistry.codesByRuleId;
