import { expect, test } from "vite-plus/test";
import { runRuleFixture } from "../../src/core/testkit.ts";
import { noClientSecretPattern } from "../../src/rule-packs/vite/rules/env.ts";

const finding = "export const exposed = import.meta.env.VITE_SECRET_TOKEN;";

test.each([
  { name: "string", prefix: 'const message = "do not edit";\n' },
  { name: "template literal", prefix: 'const message = `generated by ${"user"}`;\n' },
  { name: "regular expression", prefix: "const pattern = /@generated/;\n" },
  {
    name: "JSX content",
    prefix: 'const label = <p title="auto-generated">do not edit</p>;\n',
    file: "src/app.tsx",
  },
  {
    name: "comment after source",
    prefix: 'const label = "manual";\n// do not edit the remote response\n',
  },
  { name: "comment text inside string", prefix: 'const label = "// @generated";\n' },
])("keeps source containing generated marker text in $name", async ({ prefix, file }) => {
  const result = await runRuleFixture({
    rule: noClientSecretPattern,
    framework: "vite",
    files: { [file ?? "src/app.ts"]: `${prefix}${finding}` },
  });
  expect(result.diagnostics.map((diagnostic) => diagnostic.code)).toEqual(["VITE0009"]);
});

test.each([
  { name: "line comment", header: "// @generated\n" },
  { name: "block comment", header: "/* This file is auto-generated. */\n" },
  { name: "consecutive comments", header: "/* License */\n// Generated by the schema compiler\n" },
  { name: "shebang", header: "#!/usr/bin/env node\n// Do not edit\n" },
  { name: "BOM", header: "\uFEFF// @generated\n" },
  { name: "long comment", header: `/* @generated\n${" ".repeat(900)}*/\n` },
])("continues excluding a generated $name header", async ({ header }) => {
  const result = await runRuleFixture({
    rule: noClientSecretPattern,
    framework: "vite",
    files: { "src/app.ts": `${header}${finding}` },
  });
  expect(result.diagnostics).toEqual([]);
});

test.each([
  {
    name: "template content",
    source: `<template><p>do not edit</p></template>\n<script setup>${finding}</script>`,
    expected: 1,
  },
  {
    name: "attribute",
    source: `<template><p title="@generated" /></template>\n<script setup>${finding}</script>`,
    expected: 1,
  },
  {
    name: "HTML header",
    source: `<!-- @generated -->\n<script setup>${finding}</script>`,
    expected: 0,
  },
])("recognizes Vue file headers independently of $name", async ({ source, expected }) => {
  const result = await runRuleFixture({
    rule: noClientSecretPattern,
    framework: "vite",
    files: { "src/App.vue": source },
  });
  expect(result.diagnostics).toHaveLength(expected);
});
