import { mkdirSync, rmSync, statSync, symlinkSync, writeFileSync } from "node:fs";
import { glob, mkdtemp } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "pathe";
import { expect, test } from "vite-plus/test";
import type { ProjectInfo } from "../../src/core/primitives.ts";
import { detectProject } from "../../src/core/internal/project.ts";
import { ProjectFileWalk, selectProjectFiles } from "../../src/core/internal/project-files.ts";
import { createScanSession } from "../../src/core/internal/scan-session.ts";
import { selectScanFiles } from "../../src/core/internal/source-inventory.ts";

const sourceTree = {
  "package.json": JSON.stringify({ dependencies: { vue: "3.5.0" } }),
  "vite.config.ts": "export default {}\n",
  "vitest.config.mts": "export default {}\n",
  "doctor.config.ts": "export default {}\n",
  "src/app.vue": '<script setup lang="ts">\n</script>\n',
  "src/main.ts": "export const main = true\n",
  "src/legacy/old.js": "export const old = true\n",
  "src/feature/view.tsx": "export const view = true\n",
  "src/feature/deep/util.mjs": "export const util = true\n",
  "src/.hidden.ts": "export const hidden = true\n",
  "src/app.spec.ts": "export {}\n",
  "src/__tests__/case.ts": "export {}\n",
  "src/fixtures/input.ts": "export {}\n",
  "src/api.generated.ts": "export {}\n",
  "src/vendor.min.js": "export {}\n",
  "src/schema.ts": "// @generated by a tool\nexport const schema = {}\n",
  "src/banner.ts": "#!/usr/bin/env node\n/* Licensed MIT */\n// DO NOT EDIT\nexport {}\n",
  "src/notes.md": "# Notes\n",
  "content/index.md": "# Home\n",
  "public/sw.js": "self.x = 1\n",
  ".github/scripts/release.ts": "export {}\n",
  "node_modules/pkg/index.js": "module.exports = {}\n",
  "packages/ui/dist/index.js": "export {}\n",
  "packages/ui/coverage/report.js": "export {}\n",
  "packages/ui/generated/types.ts": "export {}\n",
  "packages/ui/src/button.vue": "<template><button /></template>\n",
  "layers/base/composables/use-thing.ts": "export const useThing = () => 1\n",
};

test("one walk selects the same default source inventory as the include patterns", async () => {
  await withFixture(sourceTree, async (root) => {
    const files = await selectScanFiles(root, {}, {}, project(root));
    expect(files.map((file) => [file.displayPath, file.sourceKind])).toEqual([
      ["layers/base/composables/use-thing.ts", "layer"],
      ["packages/ui/src/button.vue", "app"],
      ["src/app.vue", "app"],
      ["src/feature/deep/util.mjs", "app"],
      ["src/feature/view.tsx", "app"],
      ["src/legacy/old.js", "app"],
      ["src/main.ts", "app"],
      ["vite.config.ts", "app"],
      ["vitest.config.mts", "app"],
    ]);
    expect(files.every((file) => file.path === resolve(root, file.displayPath))).toBe(true);
  });
});

test("user excludes prune directories the way fs.glob does", async () => {
  await withFixture(sourceTree, async (root) => {
    const select = async (exclude: string[]) =>
      (await selectScanFiles(root, { exclude }, {}, project(root))).map((file) => file.displayPath);
    expect(await select(["src/legacy"])).not.toContain("src/legacy/old.js");
    expect(await select(["src/feature/"])).not.toContain("src/feature/view.tsx");
    expect(await select(["src/*"])).toEqual([
      "layers/base/composables/use-thing.ts",
      "packages/ui/src/button.vue",
      "vite.config.ts",
      "vitest.config.mts",
    ]);
  });
});

test.each(["@nuxt/content", "docus"])(
  "includes content Markdown when %s is installed",
  async (module) => {
    await withFixture(sourceTree, async (root) => {
      const files = await selectScanFiles(root, {}, {}, project(root, [module]));
      const paths = files.map((file) => file.displayPath);
      expect(paths).toContain("content/index.md");
      expect(paths).not.toContain("src/notes.md");
    });
  },
);

test("custom include patterns, including dot patterns, keep fs.glob results", async () => {
  await withFixture(sourceTree, async (root) => {
    const files = await selectScanFiles(
      root,
      { include: ["src/**/*.md", ".github/**/*.ts", "src/.*.ts", "./src/main.ts"] },
      {},
      project(root),
    );
    expect(files.map((file) => file.displayPath)).toEqual([
      ".github/scripts/release.ts",
      "src/.hidden.ts",
      "src/main.ts",
      "src/notes.md",
    ]);
  });
});

test.skipIf(process.platform === "win32")(
  "walked selection matches fs.glob for include and exclude patterns, including symlinks",
  async () => {
    await withFixture(sourceTree, async (root) => {
      mkdirSync(join(root, "linked/inner"), { recursive: true });
      writeFileSync(join(root, "linked/target.ts"), "");
      writeFileSync(join(root, "linked/inner/deep.js"), "");
      symlinkSync(join(root, "linked"), join(root, "src/linked"));
      symlinkSync(join(root, "linked"), join(root, "src/linked.ts"));
      symlinkSync(join(root, "linked/target.ts"), join(root, "src/target-link.ts"));
      symlinkSync(join(root, "missing.ts"), join(root, "src/dangling.ts"));
      const includes = [
        ["**/*.{vue,ts,tsx,mts,cts,js,jsx,mjs,cjs}", "vite.config.{ts,mts}"],
        ["**/*"],
        ["src/**/*.ts"],
        ["src/*/*.ts", "src/{feature,linked}/**/*.{ts,tsx,js}"],
        ["**/*.ts", "content/**/*.{md,mdc}"],
      ];
      const excludes = [
        [],
        ["src/legacy", "src/feature/"],
        ["**/deep/**", "**/*.spec.ts", "doctor.config.*"],
        ["src/*"],
      ];
      for (const include of includes) {
        for (const extra of excludes) {
          const exclude = [
            "**/node_modules/**",
            "**/dist/**",
            "**/coverage/**",
            "**/generated/**",
            ...extra,
          ];
          const walked = await selectProjectFiles(new ProjectFileWalk(root), include, exclude);
          expect(walked.sort(), JSON.stringify({ include, exclude })).toEqual(
            await globFiles(root, include, exclude),
          );
        }
      }
    });
  },
);

test.each<{ files: Record<string, string>; languages: string[] }>([
  { files: { "src/app.vue": '<script setup lang="ts"></script>' }, languages: ["typescript"] },
  { files: { "src/app.vue": "<script setup></script>" }, languages: ["javascript"] },
  {
    files: { "src/app.vue": '<script lang="tsx"></script>', "src/util.js": "" },
    languages: ["typescript", "javascript"],
  },
  {
    files: {
      "src/main.ts": "",
      "node_modules/pkg/index.js": "",
      "dist/out.js": "",
      "coverage/lcov.js": "",
      "src/generated/client.js": "",
      ".output/server.mjs": "",
      ".config/tool.js": "",
    },
    languages: ["typescript"],
  },
])("detects project languages from the shared walk: $languages", async ({ files, languages }) => {
  await withFixture({ "package.json": "{}", ...files }, async (root) => {
    expect((await detectProject(root, "vue")).languages).toEqual(languages);
  });
});

test("a later Doctor Run sees files added after the previous run", async () => {
  await withFixture({ "package.json": "{}", "src/a.ts": "export const a = 1\n" }, async (root) => {
    const first = await createScanSession({ root, framework: "vue", cache: false });
    write(root, "src/b.js", "export const b = 1\n");
    const second = await createScanSession({ root, framework: "vue", cache: false });
    expect(first.files.map((file) => file.displayPath)).toEqual(["src/a.ts"]);
    expect(first.project.languages).toEqual(["typescript"]);
    expect(second.files.map((file) => file.displayPath)).toEqual(["src/a.ts", "src/b.js"]);
    expect(second.project.languages).toEqual(["typescript", "javascript"]);

    write(root, "src/c.ts", "export const c = 1\n");
    const again = await selectScanFiles(root, second.config, {}, second.project);
    expect(again.map((file) => file.displayPath)).toEqual(["src/a.ts", "src/b.js", "src/c.ts"]);
  });
});

test("Nuxt manifest freshness is shared within a run and recomputed by the next run", async () => {
  await withFixture(
    {
      "package.json": JSON.stringify({ dependencies: { nuxt: "4.4.6" } }),
      "nuxt.config.ts": "export default defineNuxtConfig({ future: { compatibilityVersion: 4 } })",
      "server/api/hello.ts": "export default defineEventHandler(() => 'hi')\n",
    },
    async (root) => {
      write(
        root,
        ".nuxt/doctor.manifest.json",
        JSON.stringify({
          generatedAt: new Date(Date.now() + 1000).toISOString(),
          compatibilityVersion: 5,
          autoImportEnabled: true,
          nuxtConfigMtimeMs: statSync(join(root, "nuxt.config.ts")).mtimeMs,
          serverInventory: { "server/api": ["hello.ts"] },
          layers: [],
        }),
      );
      const fresh = await detectProject(root);
      expect(fresh.nuxt?.manifest?.isCurrent).toBe(true);
      expect(fresh.nuxt?.autoImportsAuthoritative).toBe(true);
      expect(fresh.nuxtCompatibility).toMatchObject({ version: 5, provenance: "manifest" });

      write(root, "server/api/new.ts", "export default defineEventHandler(() => 'new')\n");
      const stale = await detectProject(root);
      expect(stale.nuxt?.manifest?.isCurrent).toBe(false);
      expect(stale.nuxt?.autoImportsAuthoritative).toBe(false);
      expect(stale.nuxtCompatibility).toMatchObject({ version: 4, provenance: "config" });
      expect(stale.nuxt?.serverDirs.api).toEqual([
        join(root, "server/api/hello.ts"),
        join(root, "server/api/new.ts"),
      ]);
    },
  );
});

test.each(["cjs", "cts"])("detects docus from nuxt.config.%s", async (extension) => {
  await withFixture(
    {
      "package.json": JSON.stringify({ dependencies: { nuxt: "4.4.6" } }),
      [`nuxt.config.${extension}`]: "module.exports = { extends: 'docus' }\n",
      "content/index.md": "# Home\n",
    },
    async (root) => {
      const project = await detectProject(root);
      expect(project.nuxt?.modules).toEqual(expect.arrayContaining([{ name: "docus" }]));
      const files = await selectScanFiles(root, {}, {}, project);
      expect(files.map((file) => file.displayPath)).toContain("content/index.md");
    },
  );
});

function project(root: string, modules: string[] = []): ProjectInfo {
  return {
    root,
    framework: modules.length ? "nuxt" : "vue",
    ssr: false,
    vueVersion: "3.5.0",
    isMonorepo: false,
    nuxt: modules.length
      ? ({ modules: modules.map((name) => ({ name })) } as ProjectInfo["nuxt"])
      : undefined,
  };
}

async function globFiles(root: string, include: string[], exclude: string[]) {
  const files = new Set<string>();
  for (const pattern of include) {
    for await (const entry of glob(pattern, { cwd: root, exclude })) {
      const absolute = resolve(root, entry);
      if (statSync(absolute, { throwIfNoEntry: false })?.isFile()) files.add(absolute);
    }
  }
  return [...files].sort();
}

async function withFixture(files: Record<string, string>, run: (root: string) => Promise<void>) {
  const root = await mkdtemp(join(tmpdir(), "vite-doctor-project-files-"));
  try {
    for (const [file, source] of Object.entries(files)) write(root, file, source);
    await run(root);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
}

function write(root: string, file: string, source: string) {
  const absolute = join(root, file);
  mkdirSync(dirname(absolute), { recursive: true });
  writeFileSync(absolute, source);
}
