import { relative } from "pathe";
import type { RuleContext } from "@vue-doctor/core";

export const NUXT_APP_DIRS = new Set([
  "assets",
  "components",
  "composables",
  "layouts",
  "middleware",
  "pages",
  "plugins",
  "utils",
]);

export type NuxtFileClass =
  | "runtime-app"
  | "server-runtime"
  | "config-build"
  | "content-docs"
  | "generated"
  | "external-package"
  | "unknown";

export function classifyNuxtFile(ctx: RuleContext): NuxtFileClass {
  const relativePath = toPosixPath(ctx.file.relativePath);
  if (isGeneratedFile(ctx)) return "generated";
  if (isContentDocsPath(relativePath, ctx.file.sourceKind)) return "content-docs";
  if (isConfigBuildPath(relativePath)) return "config-build";
  if (ctx.helpers.isNuxtServerFile(relativePath)) return "server-runtime";
  if (isRuntimeAppPath(ctx, relativePath)) return "runtime-app";
  if (isExternalPackagePath(relativePath)) return "external-package";
  return "unknown";
}

export function isGeneratedFile(ctx: RuleContext) {
  const relativePath = toPosixPath(ctx.file.relativePath);
  if (
    relativePath.startsWith("shared/types/lexicons/") ||
    relativePath.startsWith("app/generated/") ||
    relativePath.startsWith("generated/")
  )
    return true;
  return /@generated|generated by|do not edit|auto-generated/i.test(ctx.file.text.slice(0, 800));
}

export function isRuntimeAppFile(ctx: RuleContext) {
  return classifyNuxtFile(ctx) === "runtime-app";
}

export function isServerRuntimeFile(ctx: RuleContext) {
  return classifyNuxtFile(ctx) === "server-runtime";
}

export function isContentDocsFile(ctx: RuleContext) {
  return classifyNuxtFile(ctx) === "content-docs";
}

export function isConfigBuildFile(ctx: RuleContext) {
  return classifyNuxtFile(ctx) === "config-build";
}

export function isNuxtRuntimeFile(ctx: RuleContext) {
  return isRuntimeAppFile(ctx);
}

export function isExplicitlyScannedByNuxt(ctx: RuleContext, kind: "imports" | "shared") {
  if (isGeneratedFile(ctx)) return true;
  const manifest = ctx.project.nuxt?.manifest;
  if (!manifest) return false;
  const roots = kind === "imports" ? manifest.importsDirs : manifest.sharedScanRoots;
  if (!roots.length) return false;
  const relativePath = toPosixPath(relative(ctx.project.root, ctx.file.path));
  return roots
    .map((root) => normalizeScanRoot(ctx, root))
    .filter(Boolean)
    .filter((root) =>
      kind === "imports" && !root.includes("*")
        ? root !== "app/composables" && root !== "composables"
        : root !== "shared/utils" && root !== "shared/types",
    )
    .some((root) => matchesScanRoot(relativePath, root));
}

export function isExplicitPlugin(ctx: RuleContext) {
  const manifest = ctx.project.nuxt?.manifest;
  if (!manifest?.hasManifest) return false;
  return manifest.pluginFiles.some((file) => resolveSameFile(file, ctx.file.path));
}

export function resolveSameFile(a: string, b: string) {
  return toPosixPath(a) === toPosixPath(b);
}

export function toPosixPath(path: string) {
  return path.replace(/\\/g, "/");
}

function isRuntimeAppPath(ctx: RuleContext, relativePath: string) {
  if (ctx.file.sourceKind === "module") return false;
  const roots = ctx.project.nuxt?.appRoots;
  if (roots?.length) {
    const relativeRoots = roots
      .map((root: string) => toPosixPath(relative(ctx.project.root, root)))
      .filter((root: string) => root && root !== ".");
    if (relativeRoots.length) {
      return relativeRoots.some(
        (root: string) => relativePath === root || relativePath.startsWith(`${root}/`),
      );
    }
  }

  if (relativePath.startsWith("app/")) return true;
  const [first] = relativePath.split("/");
  return !!first && NUXT_APP_DIRS.has(first);
}

function isContentDocsPath(relativePath: string, sourceKind: string | undefined) {
  return (
    sourceKind === "content" ||
    /\.(md|mdc|markdown)$/.test(relativePath) ||
    relativePath.startsWith("content/")
  );
}

function isConfigBuildPath(relativePath: string) {
  return (
    /(^|\/)(nuxt|content|vite|vitest|eslint|tailwind|uno|app)\.config\.[cm]?[jt]s$/.test(
      relativePath,
    ) ||
    /(^|\/)package\.json$/.test(relativePath) ||
    /^(config|scripts|tools|test|tests|\.github)\//.test(relativePath)
  );
}

function isExternalPackagePath(relativePath: string) {
  return /^(cli|packages|connector|docs)\//.test(relativePath);
}

function normalizeScanRoot(ctx: RuleContext, root: string) {
  let normalized = toPosixPath(root);
  const projectRoot = `${toPosixPath(ctx.project.root)}/`;
  if (normalized.startsWith(projectRoot)) normalized = normalized.slice(projectRoot.length);
  else normalized = toPosixPath(relative(ctx.project.root, normalized));
  normalized = normalized.replace(/^~\//, "app/").replace(/^@\//, "app/");
  normalized = normalized.replace(/^\.\//, "");
  if (normalized.startsWith("composables/") && ctx.file.relativePath.startsWith("app/composables/"))
    return `app/${normalized}`;
  return normalized;
}

function matchesScanRoot(relativePath: string, root: string) {
  if (root.includes("*")) return globToRegExp(root).test(relativePath);
  return relativePath === root || relativePath.startsWith(`${root}/`);
}

function globToRegExp(glob: string) {
  const pattern = glob
    .split("/")
    .map((part) =>
      part === "**" ? ".*" : part.replace(/[.+?^${}()|[\]\\]/g, "\\$&").replaceAll("*", "[^/]*"),
    )
    .join("/");
  return new RegExp(`^${pattern}$`);
}
