import { defineDoctorDiagnostics, doctorDiagnosticsHost } from "./diagnostics.js";

export const allDoctorDiagnosticRegistry = defineDoctorDiagnostics([
  { code: "DOC9999", ruleId: "doctor/external-rule-diagnostic" },
  { code: "DOC0001", ruleId: "workspace/dead-code/circular-dependency" },
  { code: "DOC0002", ruleId: "workspace/dead-code/duplicate-export" },
  { code: "DOC0003", ruleId: "workspace/dead-code/unlisted-dependency" },
  { code: "DOC0004", ruleId: "workspace/dead-code/unresolved-import" },
  { code: "DOC0005", ruleId: "workspace/dead-code/unused-dependency" },
  { code: "DOC0006", ruleId: "workspace/dead-code/unused-export" },
  { code: "DOC0007", ruleId: "workspace/dead-code/unused-file" },
  { code: "DOC0008", ruleId: "workspace/dead-code/unused-type-export" },
  { code: "DOC0009", ruleId: "workspace/duplication/exact-clone" },
  { code: "DOC0010", ruleId: "workspace/health/high-cyclomatic-complexity" },
  { code: "DOC0011", ruleId: "workspace/health/high-fan-out" },
  { code: "DOC0012", ruleId: "doctor/internal/duplicate-diagnostic-code", docs: false },
  { code: "DOC0013", ruleId: "doctor/internal/missing-diagnostic-code", docs: false },
  { code: "DOC0014", ruleId: "doctor/internal/missing-diagnostic-name", docs: false },
  { code: "DOC0015", ruleId: "doctor/rule-pack/missing-recommended-preset", docs: false },
  { code: "DOC0016", ruleId: "doctor/config/invalid-extends-entry", docs: false },
  { code: "DOC0017", ruleId: "doctor/config/unknown-rule-pack", docs: false },
  { code: "DOC0018", ruleId: "doctor/config/unknown-preset", docs: false },
  { code: "DOC0019", ruleId: "doctor/config/invalid-rule-severity", docs: false },
  { code: "DOC0020", ruleId: "doctor/config/invalid-rule-config", docs: false },
  { code: "DOC0021", ruleId: "doctor/internal/missing-diagnostic-fix", docs: false },
  { code: "VUE0001", ruleId: "vue/i18n/no-untranslated-text" },
  { code: "VUE0002", ruleId: "vue/i18n/no-unused-translations" },
  { code: "VUE0003", ruleId: "vue/lifecycle/no-mutation-in-onupdated" },
  { code: "VUE0004", ruleId: "vue/lifecycle/require-cleanup" },
  { code: "VUE0005", ruleId: "vue/reactivity/defineprops-watch-getter" },
  { code: "VUE0006", ruleId: "vue/reactivity/no-ref-as-operand" },
  { code: "VUE0007", ruleId: "vue/reactivity/no-setup-props-destructure" },
  { code: "VUE0008", ruleId: "vue/reactivity/prefer-composable-ref-return" },
  { code: "VUE0009", ruleId: "vue/security/restrict-v-html" },
  { code: "VUE0010", ruleId: "vue/ssr/data-allow-mismatch-surgical" },
  { code: "VUE0011", ruleId: "vue/ssr/no-browser-api-in-setup" },
  { code: "VUE0012", ruleId: "vue/ssr/no-random-or-local-time-render" },
  { code: "VUE0013", ruleId: "vue/ssr/use-id-for-stable-ids" },
  { code: "VUE0014", ruleId: "vue/style/prefer-define-model" },
  { code: "VUE0015", ruleId: "vue/style/prefer-props-destructure-defaults" },
  { code: "VUE0016", ruleId: "vue/style/prefer-type-props" },
  { code: "VUE0017", ruleId: "vue/template/prefer-use-template-ref" },
  { code: "VUE0018", ruleId: "vue/watch/no-async-watcheffect-after-await-read" },
  { code: "VUE0019", ruleId: "vue/watch/no-onwatchercleanup-after-await" },
  { code: "VUE0020", ruleId: "vue/watch/require-post-flush-for-dom-read" },
  { code: "VUE0021", ruleId: "vue/watch/require-side-effect-cleanup" },
  { code: "VUE0022", ruleId: "vue/template/html-button-has-type" },
  { code: "VUE0023", ruleId: "vue/template/prefer-same-name-prop-shorthand" },
  { code: "VUE0024", ruleId: "vue/template/prefer-true-attribute-shorthand" },
  { code: "VUE0025", ruleId: "vue/lifecycle/prefer-use-event-listener" },
  { code: "VITE0001", ruleId: "vite/assets/no-dynamic-new-url" },
  { code: "VITE0002", ruleId: "vite/assets/no-public-src-import" },
  { code: "VITE0003", ruleId: "vite/assets/no-src-absolute-public-url" },
  { code: "VITE0004", ruleId: "vite/define/no-runtime-object-define" },
  { code: "VITE0005", ruleId: "vite/define/no-secret-define" },
  { code: "VITE0006", ruleId: "vite/define/no-untyped-define" },
  { code: "VITE0007", ruleId: "vite/define/no-unused-define" },
  { code: "VITE0008", ruleId: "vite/env/no-broad-env-prefix" },
  { code: "VITE0009", ruleId: "vite/env/no-client-secret-pattern" },
  { code: "VITE0010", ruleId: "vite/env/no-empty-env-prefix" },
  { code: "VITE0011", ruleId: "vite/env/no-untyped-env" },
  { code: "VITE0012", ruleId: "vite/env/prefer-direct-import-meta-env-access" },
  { code: "VITE0013", ruleId: "vite/hmr/require-dispose-for-side-effects" },
  { code: "VITE0014", ruleId: "vite/plugin/prefer-transform-filter" },
  { code: "VITE0015", ruleId: "vite/plugin/require-name" },
  { code: "VITE0016", ruleId: "vite/server/no-broad-fs-allow" },
  { code: "VITE0017", ruleId: "vite/server/no-disabled-fs-strict" },
  { code: "VITE0018", ruleId: "vite/ssr/no-browser-global-in-ssr-entry" },
  { code: "VITE0019", ruleId: "vite/worker/no-dynamic-worker-url" },
  { code: "VITE0020", ruleId: "vite/worker/no-node-api-in-worker" },
  { code: "VITE0021", ruleId: "vite/worker/require-worker-url-pattern" },
  { code: "NITRO0001", ruleId: "nitro/context/no-navigateto-in-nitro" },
  { code: "NITRO0002", ruleId: "nitro/context/no-usenuxtapp-in-nitro" },
  { code: "NITRO0003", ruleId: "nitro/request/prefer-assert-method" },
  { code: "NITRO0004", ruleId: "nitro/request/prefer-get-request-ip" },
  { code: "NITRO0005", ruleId: "nitro/request/prefer-validated-body" },
  { code: "NITRO0006", ruleId: "nitro/request/prefer-validated-query" },
  { code: "NITRO0007", ruleId: "nitro/request/prefer-validated-router-params" },
  { code: "NITRO0008", ruleId: "nitro/runtime/require-event-runtime-config-in-server" },
  { code: "NITRO0009", ruleId: "nitro/server/no-browser-api" },
  { code: "NITRO0010", ruleId: "nitro/server/no-client-composables" },
  { code: "NITRO0011", ruleId: "nitro/server/prefer-event-fetch" },
  { code: "NITRO0012", ruleId: "nitro/request/prefer-route-method-suffix" },
  { code: "NUXT0001", ruleId: "docus/appconfig/no-unknown-key" },
  { code: "NUXT0002", ruleId: "docus/layers/no-empty-app-vue-shadow" },
  { code: "NUXT0003", ruleId: "nuxt-better-auth/require-standard-auth-handler-mount" },
  { code: "NUXT0004", ruleId: "nuxt-content/links/no-broken-internal-to-link" },
  { code: "NUXT0005", ruleId: "nuxt-content/no-querycontent-legacy-api" },
  { code: "NUXT0006", ruleId: "nuxt-image/prefer-nuxtimg" },
  { code: "NUXT0007", ruleId: "nuxt-image/prefer-nuxtpicture-for-formats" },
  { code: "NUXT0008", ruleId: "nuxt-image/prefer-responsive-dimensions" },
  { code: "NUXT0009", ruleId: "nuxt-image/require-alt" },
  { code: "NUXT0010", ruleId: "nuxt-scripts/no-raw-third-party-script-tag" },
  { code: "NUXT0011", ruleId: "nuxt-scripts/no-third-party-config-script" },
  { code: "NUXT0012", ruleId: "nuxt-scripts/no-third-party-usehead-script" },
  { code: "NUXT0013", ruleId: "nuxt-ui/prefer-u-button" },
  { code: "NUXT0014", ruleId: "nuxt-ui/prefer-u-form-controls" },
  { code: "NUXT0015", ruleId: "nuxt-ui/require-uapp-root" },
  { code: "NUXT0016", ruleId: "nuxt/async-data-explicit-key-for-refreshable" },
  { code: "NUXT0017", ruleId: "nuxt/async-data-handler-pure" },
  { code: "NUXT0018", ruleId: "nuxt/async-data-no-mutation-methods" },
  { code: "NUXT0019", ruleId: "nuxt/composables/no-nested-autoimport-assumption" },
  { code: "NUXT0020", ruleId: "nuxt/context/no-composable-after-await" },
  { code: "NUXT0021", ruleId: "nuxt/context/no-legacy-process-client-server" },
  { code: "NUXT0022", ruleId: "nuxt/fetch/create-usefetch-must-be-exported-in-scanned-dir" },
  { code: "NUXT0023", ruleId: "nuxt/fetch/forward-auth-headers-ssr" },
  { code: "NUXT0024", ruleId: "nuxt/fetch/keyed-composable-registration-required" },
  { code: "NUXT0025", ruleId: "nuxt/fetch/no-await-inside-custom-wrapper" },
  { code: "NUXT0026", ruleId: "nuxt/fetch/no-raw-fetch-in-setup" },
  { code: "NUXT0027", ruleId: "nuxt/fetch/prefer-create-use-fetch" },
  { code: "NUXT0028", ruleId: "nuxt/fetch/require-stable-asyncdata-key" },
  { code: "NUXT0029", ruleId: "nuxt/hydration/no-browser-global-in-universal-code" },
  { code: "NUXT0030", ruleId: "nuxt/hydration/no-browser-side-effects-in-setup" },
  { code: "NUXT0031", ruleId: "nuxt/hydration/no-client-conditional-in-template" },
  {
    code: "NUXT0032",
    ruleId: "nuxt/hydration/no-time-dependent-render-without-nuxttime-or-clientonly",
  },
  { code: "NUXT0033", ruleId: "nuxt/hydration/prefer-usecookie-for-initial-client-state" },
  { code: "NUXT0034", ruleId: "nuxt/imports/no-auto-import-collision" },
  { code: "NUXT0035", ruleId: "nuxt/imports/no-conflicting-usefetch-import" },
  { code: "NUXT0036", ruleId: "nuxt/imports/no-explicit-auto-import" },
  { code: "NUXT0037", ruleId: "nuxt/middleware/no-route-middleware-api-security" },
  { code: "NUXT0038", ruleId: "nuxt/no-global-refresh-without-justification" },
  { code: "NUXT0039", ruleId: "nuxt/no-manual-action-usefetch" },
  { code: "NUXT0040", ruleId: "nuxt/no-mutation-toast-in-usefetch-callback" },
  { code: "NUXT0041", ruleId: "nuxt/plugins/no-subdir-auto-registration-assumption" },
  { code: "NUXT0042", ruleId: "nuxt/post-fetch-requires-readonly-marker" },
  { code: "NUXT0043", ruleId: "nuxt/preview-mode-global-refresh" },
  { code: "NUXT0044", ruleId: "nuxt/project/prefer-app-directory-placement" },
  { code: "NUXT0045", ruleId: "nuxt/routing/no-hash-sensitive-route-fullpath-in-ssr-markup" },
  { code: "NUXT0046", ruleId: "nuxt/routing/no-route-object-page-key" },
  { code: "NUXT0047", ruleId: "nuxt/routing/no-router-navigation-in-setup" },
  { code: "NUXT0048", ruleId: "nuxt/routing/no-useroute-in-middleware" },
  { code: "NUXT0049", ruleId: "nuxt/routing/prefer-nuxt-useroute" },
  { code: "NUXT0050", ruleId: "nuxt/routing/prefer-nuxtlink" },
  { code: "NUXT0051", ruleId: "nuxt/routing/prefer-nuxtpage-over-routerview" },
  { code: "NUXT0052", ruleId: "nuxt/routing/return-navigateto-in-middleware" },
  { code: "NUXT0053", ruleId: "nuxt/runtime/no-plain-env-in-app-code" },
  { code: "NUXT0054", ruleId: "nuxt/runtime/no-secret-in-public-config" },
  { code: "NUXT0055", ruleId: "nuxt/security/no-unsafe-usehead-script" },
  { code: "NUXT0056", ruleId: "nuxt/security/prefer-useheadsafe-for-untrusted-values" },
  { code: "NUXT0057", ruleId: "nuxt/seo/prefer-seo-composables" },
  { code: "NUXT0058", ruleId: "nuxt/shared/no-nested-shared-autoimport-assumption" },
  { code: "NUXT0059", ruleId: "nuxt/shared/no-vue-or-nitro-context-in-shared" },
  { code: "NUXT0060", ruleId: "nuxt/state/no-nonserializable-usestate" },
  { code: "NUXT0061", ruleId: "nuxt/state/prefer-explicit-usestate-key-in-exported-composables" },
  { code: "NUXT0062", ruleId: "nuxthub/no-personalized-cached-handler" },
  { code: "NUXT0063", ruleId: "nuxthub/prefer-cached-event-handler" },
  { code: "NUXT0064", ruleId: "vueuse/no-nuxt-auto-import-collision" },
  { code: "NUXT0065", ruleId: "vueuse/prefer-use-observers" },
  { code: "NUXT0066", ruleId: "vueuse/prefer-use-scroll-and-element" },
  { code: "NUXT0067", ruleId: "vueuse/prefer-use-storage" },
  { code: "NUXT0068", ruleId: "vueuse/prefer-use-timers" },
  { code: "NUXT0069", ruleId: "vueuse/prefer-usebreakpoints" },
  { code: "NUXT0070", ruleId: "vueuse/prefer-useclipboard" },
  { code: "NUXT0071", ruleId: "vueuse/prefer-useevent-listener" },
  { code: "NUXT0072", ruleId: "vueuse/prefer-usewindow-size" },
]);

export const allDiagnosticCodesByRuleId = allDoctorDiagnosticRegistry.codesByRuleId;
doctorDiagnosticsHost.register(allDoctorDiagnosticRegistry);
export const allDiagnostics = allDoctorDiagnosticRegistry.diagnostics;
