import { closeSync, openSync, readSync, statSync } from "node:fs";
import { glob } from "node:fs/promises";
import { matchesGlob } from "node:path";
import { relative, resolve } from "pathe";
import type { DoctorConfig } from "../config.js";
import type { DoctorRunOptions } from "../config.js";
import type { ProjectInfo, SourceFileHandle } from "../primitives.js";
import {
  collectGitChangeInventory,
  type AvailableGitChangeInventory,
  type ChangedLineRange,
  type GitChangeInventory,
  type UnavailableGitChangeInventory,
} from "./git-change-ranges.js";

const DEFAULT_INCLUDE = [
  "**/*.{vue,ts,tsx,mts,cts,js,jsx,mjs,cjs}",
  "vite.config.{ts,js,mjs,cjs,mts,cts}",
  "vitest.config.{ts,js,mjs,cjs,mts,cts}",
];
const CONTENT_INCLUDE = ["content/**/*.{md,mdc}"];
const GENERATED_HEADER_BYTES = 800;
const GENERATED_HEADER_PATTERN = /@generated|generated by|do not edit|auto-generated/i;
const DEFAULT_EXCLUDE = [
  "**/node_modules/**",
  "**/.nuxt/**",
  "**/.next/**",
  "**/.output/**",
  "**/dist/**",
  "**/coverage/**",
  "**/public/**",
  "**/generated/**",
  "**/*.generated.{ts,tsx,mts,cts,js,jsx,mjs,cjs,vue}",
  "**/*.min.{ts,tsx,mts,cts,js,jsx,mjs,cjs}",
  "**/{test,tests,__tests__,__snapshots__,fixtures,test-d,typetest,__typetest__,type-tests,dts-test,dtslint}/**",
  "**/*.{test,spec}.{ts,tsx,mts,cts,js,jsx,mjs,cjs,vue}",
  "doctor.config.*",
];

export interface ScanFileEntry {
  path: string;
  displayPath: string;
  sourceKind: SourceFileHandle["sourceKind"];
  moduleName?: string;
  reportEligibility?: {
    kind: "changed-lines";
    ranges: ChangedLineRange[];
  };
}

export interface SourceInventorySelection {
  files: ScanFileEntry[];
  git?: GitChangeInventory;
}

export class GitChangeUnavailableError extends Error {
  readonly inventory: UnavailableGitChangeInventory;

  constructor(inventory: UnavailableGitChangeInventory) {
    super(inventory.message);
    this.name = "GitChangeUnavailableError";
    this.inventory = inventory;
  }
}

export async function selectSourceInventory(
  root: string,
  config: DoctorConfig,
  options: DoctorRunOptions,
  project: ProjectInfo,
): Promise<SourceInventorySelection> {
  if (options.changed || options.since) {
    const include = config.include ?? defaultIncludeForProject(project);
    const exclude = [...DEFAULT_EXCLUDE, ...(config.exclude ?? [])];
    const git = await collectGitChangeInventory(
      root,
      options.since,
      (path) =>
        include.some((pattern) => matchesGlob(path, pattern)) &&
        !exclude.some((pattern) => matchesGlob(path, pattern)),
    );
    if (git.status === "unavailable") return { files: [], git };
    return { files: selectChangedFiles(root, config, project, git), git };
  }

  return { files: await selectAllFiles(root, config, project) };
}

export async function selectScanFiles(
  root: string,
  config: DoctorConfig,
  options: DoctorRunOptions,
  project: ProjectInfo,
): Promise<ScanFileEntry[]> {
  const selection = await selectSourceInventory(root, config, options, project);
  if (selection.git?.status === "unavailable") {
    throw new GitChangeUnavailableError(selection.git);
  }
  return selection.files;
}

async function selectAllFiles(
  root: string,
  config: DoctorConfig,
  project: ProjectInfo,
): Promise<ScanFileEntry[]> {
  const files = new Map<string, ScanFileEntry>();
  const exclude = [...DEFAULT_EXCLUDE, ...(config.exclude ?? [])];
  const include = config.include ?? defaultIncludeForProject(project);
  for (const pattern of include) {
    for await (const entry of glob(pattern, { cwd: root, exclude })) {
      if (typeof entry !== "string") continue;
      const absolute = resolve(root, entry);
      if (isScannableFile(absolute)) files.set(absolute, createAppFileEntry(root, entry));
    }
  }

  for (const source of project.nuxt?.moduleSources ?? []) {
    const include = source.include?.length ? source.include : DEFAULT_INCLUDE;
    const moduleExclude = [...DEFAULT_EXCLUDE, ...(source.exclude ?? [])];
    for (const pattern of include) {
      for await (const entry of glob(pattern, { cwd: source.root, exclude: moduleExclude })) {
        if (typeof entry !== "string") continue;
        const absolute = resolve(source.root, entry);
        if (!isScannableFile(absolute)) continue;
        files.set(absolute, {
          path: absolute,
          displayPath: `${source.module}:${relative(source.root, absolute)}`,
          sourceKind: "module",
          moduleName: source.module,
        });
      }
    }
  }

  return [...files.values()].sort((a, b) => a.displayPath.localeCompare(b.displayPath));
}

function selectChangedFiles(
  root: string,
  config: DoctorConfig,
  project: ProjectInfo,
  git: AvailableGitChangeInventory,
): ScanFileEntry[] {
  const include = config.include ?? defaultIncludeForProject(project);
  const exclude = [...DEFAULT_EXCLUDE, ...(config.exclude ?? [])];
  return git.files
    .filter((change) => change.path)
    .filter(
      (change) =>
        include.some((pattern) => matchesGlob(change.path!, pattern)) &&
        !exclude.some((pattern) => matchesGlob(change.path!, pattern)),
    )
    .filter((change) => isScannableFile(resolve(root, change.path!)))
    .map((change) => ({
      ...createAppFileEntry(root, change.path!),
      reportEligibility: {
        kind: "changed-lines" as const,
        ranges: change.reportRanges,
      },
    }))
    .sort((left, right) => left.displayPath.localeCompare(right.displayPath));
}

function isScannableFile(file: string): boolean {
  return Boolean(statSync(file, { throwIfNoEntry: false })?.isFile()) && !hasGeneratedHeader(file);
}

function hasGeneratedHeader(file: string): boolean {
  const descriptor = openSync(file, "r");
  try {
    const buffer = Buffer.alloc(GENERATED_HEADER_BYTES);
    const bytesRead = readSync(descriptor, buffer, 0, buffer.length, 0);
    return GENERATED_HEADER_PATTERN.test(buffer.toString("utf8", 0, bytesRead));
  } finally {
    closeSync(descriptor);
  }
}

function defaultIncludeForProject(project: ProjectInfo): string[] {
  if (hasContentFiles(project)) return [...DEFAULT_INCLUDE, ...CONTENT_INCLUDE];
  return DEFAULT_INCLUDE;
}

function hasContentFiles(project: ProjectInfo): boolean {
  const moduleNames = new Set((project.nuxt?.modules ?? []).map((module) => module.name));
  return moduleNames.has("@nuxt/content") || moduleNames.has("docus");
}

function createAppFileEntry(root: string, file: string): ScanFileEntry {
  const absolute = resolve(root, file);
  return {
    path: absolute,
    displayPath: relative(root, absolute),
    sourceKind: detectAppSourceKind(root, absolute),
  };
}

function detectAppSourceKind(root: string, file: string): SourceFileHandle["sourceKind"] {
  const relativePath = relative(root, file);
  return relativePath.startsWith("layers/") ? "layer" : "app";
}
