import { join, relative, resolve } from "pathe";
import type { RuleContext } from "../../../../core/index.js";

export const NUXT_APP_DIRS = new Set([
  "assets",
  "components",
  "composables",
  "layouts",
  "middleware",
  "pages",
  "plugins",
  "utils",
]);

export type NuxtFileClass =
  | "runtime-app"
  | "server-runtime"
  | "config-build"
  | "content-docs"
  | "generated"
  | "external-package"
  | "unknown";

interface NuxtAppSource {
  root: string;
  srcDir: string;
  serverDir: string;
}

export function classifyNuxtFile(ctx: RuleContext): NuxtFileClass {
  const relativePath = toPosixPath(ctx.file.relativePath);
  if (isGeneratedFile(ctx)) return "generated";
  if (isContentDocsPath(relativePath, ctx.file.sourceKind)) return "content-docs";
  const file = toPosixPath(resolve(ctx.project.root, ctx.file.path));
  const source = owningNuxtAppSource(ctx, file);
  const appPath = source ? relative(source.root, file) : relativePath;
  if (isConfigBuildPath(relativePath) || isConfigBuildPath(appPath)) return "config-build";
  if (
    ctx.helpers.isNuxtServerFile(relativePath) ||
    (source && isNuxtServerPath(ctx, source, file, appPath))
  )
    return "server-runtime";
  if (source && ctx.file.sourceKind !== "module" && isRuntimeAppPath(source, file, appPath))
    return "runtime-app";
  if (isExternalPackagePath(relativePath)) return "external-package";
  return "unknown";
}

export function isGeneratedFile(ctx: RuleContext) {
  const relativePath = toPosixPath(ctx.file.relativePath);
  if (
    relativePath.startsWith("shared/types/lexicons/") ||
    relativePath.startsWith("app/generated/") ||
    relativePath.startsWith("generated/")
  )
    return true;
  return /@generated|generated by|do not edit|auto-generated/i.test(ctx.file.text.slice(0, 800));
}

export function isRuntimeAppFile(ctx: RuleContext) {
  return classifyNuxtFile(ctx) === "runtime-app";
}

export function isServerRuntimeFile(ctx: RuleContext) {
  return classifyNuxtFile(ctx) === "server-runtime";
}

export function isContentDocsFile(ctx: RuleContext) {
  return classifyNuxtFile(ctx) === "content-docs";
}

export function isConfigBuildFile(ctx: RuleContext) {
  return classifyNuxtFile(ctx) === "config-build";
}

export function isNuxtRuntimeFile(ctx: RuleContext) {
  return isRuntimeAppFile(ctx);
}

export function isExplicitlyScannedByNuxt(ctx: RuleContext, kind: "imports" | "shared") {
  if (isGeneratedFile(ctx)) return true;
  const manifest = ctx.project.nuxt?.manifest;
  if (!manifest) return false;
  const roots = kind === "imports" ? manifest.importsDirs : manifest.sharedScanRoots;
  if (!roots.length) return false;
  const relativePath = toPosixPath(relative(ctx.project.root, ctx.file.path));
  return roots
    .map((root) => normalizeScanRoot(ctx, root))
    .filter(Boolean)
    .filter((root) =>
      kind === "imports" && !root.includes("*")
        ? root !== "app/composables" && root !== "composables"
        : root !== "shared/utils" && root !== "shared/types",
    )
    .some((root) => matchesScanRoot(relativePath, root));
}

export function isExplicitPlugin(ctx: RuleContext) {
  const manifest = ctx.project.nuxt?.manifest;
  if (!manifest?.hasManifest) return false;
  return manifest.pluginFiles.some((file) => resolveSameFile(file, ctx.file.path));
}

export function resolveSameFile(a: string, b: string) {
  return toPosixPath(a) === toPosixPath(b);
}

export function toPosixPath(path: string) {
  return path.replace(/\\/g, "/");
}

function owningNuxtAppSource(ctx: RuleContext, file: string) {
  let owner: NuxtAppSource | undefined;
  for (const source of nuxtAppSources(ctx)) {
    if (isInside(file, source.root) && (!owner || source.root.length > owner.root.length))
      owner = source;
  }
  return owner;
}

// Nuxt roots come from manifest layers or every detected nuxt.config, so nested apps such as
// docs/ each get their own srcDir instead of treating the whole app root as app code.
function nuxtAppSources(ctx: RuleContext): NuxtAppSource[] {
  const key = "nuxt:app-sources";
  const cached = ctx.cache.get<NuxtAppSource[]>(key);
  if (cached) return cached;
  const nuxt = ctx.project.nuxt;
  const layers = (nuxt?.layers ?? []).map((layer) => ({
    ...layer,
    root: toPosixPath(resolve(ctx.project.root, layer.root)),
  }));
  const primaryRoot =
    layers.find((layer) => layer.priority === 0)?.root ?? toPosixPath(ctx.project.root);
  const roots = new Set([
    ...(nuxt?.appRoots ?? []).map((root) => toPosixPath(resolve(ctx.project.root, root))),
    ...layers.map((layer) => layer.root),
    primaryRoot,
  ]);
  const sources = [...roots].map((root): NuxtAppSource => {
    const layer = layers.find((candidate) => candidate.root === root);
    const srcDir = layer?.srcDir
      ? resolve(root, layer.srcDir)
      : root === primaryRoot && nuxt?.appDir
        ? resolve(ctx.project.root, nuxt.appDir)
        : ctx.fs.exists(join(root, "app"))
          ? join(root, "app")
          : root;
    return {
      root,
      srcDir: toPosixPath(srcDir),
      serverDir: toPosixPath(
        layer?.serverDir ? resolve(root, layer.serverDir) : join(root, "server"),
      ),
    };
  });
  ctx.cache.set(key, sources);
  return sources;
}

function isNuxtServerPath(ctx: RuleContext, source: NuxtAppSource, file: string, appPath: string) {
  return (
    ctx.helpers.isNuxtServerFile(appPath) ||
    isInside(file, source.serverDir) ||
    isInside(file, `${source.srcDir}/server`)
  );
}

function isRuntimeAppPath(source: NuxtAppSource, file: string, appPath: string) {
  if (source.srcDir !== source.root) return isInside(file, source.srcDir);
  if (appPath.startsWith("app/") || /^(app|error)\.vue$/.test(appPath)) return true;
  const [first] = appPath.split("/");
  return !!first && NUXT_APP_DIRS.has(first);
}

function isInside(file: string, dir: string) {
  return file === dir || file.startsWith(`${dir}/`);
}

function isContentDocsPath(relativePath: string, sourceKind: string | undefined) {
  return (
    sourceKind === "content" ||
    /\.(md|mdc|markdown)$/.test(relativePath) ||
    relativePath.startsWith("content/")
  );
}

function isConfigBuildPath(relativePath: string) {
  return (
    /(^|\/)(nuxt|content|vite|vitest|eslint|tailwind|uno|app)\.config\.[cm]?[jt]s$/.test(
      relativePath,
    ) ||
    /(^|\/)package\.json$/.test(relativePath) ||
    /^(config|scripts|tools|test|tests|\.github)\//.test(relativePath)
  );
}

function isExternalPackagePath(relativePath: string) {
  return /^(cli|packages|connector|docs)\//.test(relativePath);
}

function normalizeScanRoot(ctx: RuleContext, root: string) {
  let normalized = toPosixPath(root);
  const projectRoot = `${toPosixPath(ctx.project.root)}/`;
  if (normalized.startsWith(projectRoot)) normalized = normalized.slice(projectRoot.length);
  else normalized = toPosixPath(relative(ctx.project.root, normalized));
  normalized = normalized.replace(/^~\//, "app/").replace(/^@\//, "app/");
  normalized = normalized.replace(/^\.\//, "");
  if (normalized.startsWith("composables/") && ctx.file.relativePath.startsWith("app/composables/"))
    return `app/${normalized}`;
  return normalized;
}

function matchesScanRoot(relativePath: string, root: string) {
  if (root.includes("*")) return globToRegExp(root).test(relativePath);
  return relativePath === root || relativePath.startsWith(`${root}/`);
}

function globToRegExp(glob: string) {
  const pattern = glob
    .split("/")
    .map((part) =>
      part === "**" ? ".*" : part.replace(/[.+?^${}()|[\]\\]/g, "\\$&").replaceAll("*", "[^/]*"),
    )
    .join("/");
  return new RegExp(`^${pattern}$`);
}
