import { basename, dirname, extname, join, relative, resolve } from "pathe";
import ts from "typescript";
import { createRule, type RuleContext } from "../../../core/index.js";
import { parseScript } from "../../../core/internal/script.js";
import { diagnostics } from "../../../diagnostics.js";
import type { AnyNode } from "./shared.js";

const MIN_BARREL_MODULES = 3;
const MAX_TRACE_DEPTH = 8;
const SCRIPT_EXTENSIONS = [".ts", ".tsx", ".mts", ".cts", ".js", ".jsx", ".mjs", ".cjs"];
const RESOLVE_EXTENSIONS = [...SCRIPT_EXTENSIONS, ".vue"];
const GENERATED_PATH_RE =
  /(?:^|\/)(?:node_modules|\.nuxt|\.output|\.vite|\.svelte-kit|dist|generated|__generated__)\//;
const GENERATED_FILE_RE = /\.(?:d\.[cm]?ts|gen\.[cm]?[jt]sx?|generated\.[cm]?[jt]sx?)$/;
const GENERATED_HEADER_RE = /@generated|auto-generated|autogenerated|do not edit/i;

type Binding =
  | { kind: "local"; type: boolean }
  | { kind: "reexport"; from: string; name: string; type: boolean }
  | { kind: "unknown" };

interface ModuleInfo {
  reexportOnly: boolean;
  exports: Map<string, Binding>;
  stars: Array<string | null>;
  barrelModules: Set<string> | null;
}

interface Origin {
  file: string;
  name: string;
  type: boolean;
}

export const noBarrelFiles = createRule({
  meta: {
    id: "vite/imports/no-barrel-files",
    title: "Import from defining modules instead of barrel files",
    category: "imports",
    severity: "info",
    docsUrl: "https://vite.dev/guide/performance#avoid-barrel-files",
    requires: { script: true },
  },
  create(ctx) {
    if (isGenerated(ctx.file.relativePath, ctx.file.text)) return;
    return {
      ImportDeclaration(node: AnyNode) {
        if (node.importKind === "type") return;
        const specifier = node.source?.value;
        if (typeof specifier !== "string" || !node.specifiers?.length) return;
        const barrel = resolveSpecifier(ctx, ctx.file.path, specifier);
        if (!barrel || barrel === ctx.file.path) return;
        const info = moduleInfo(ctx, barrel);
        if (!info?.barrelModules || isPackageEntry(ctx, barrel)) return;

        const imports: Array<{ local: string; origin: Origin }> = [];
        for (const item of node.specifiers) {
          if (item.type === "ImportNamespaceSpecifier") return;
          if (item.importKind === "type") continue;
          const imported =
            item.type === "ImportDefaultSpecifier" ? "default" : exportName(item.imported);
          if (!imported) return;
          const origin = traceExport(ctx, barrel, imported, 0, new Set());
          if (!origin) return;
          if (!origin.type) imports.push({ local: item.local.name, origin });
        }
        const needed = new Set(imports.map((entry) => entry.origin.file));
        if (!needed.size || needed.size >= info.barrelModules.size) return;
        if (needed.has(ctx.file.path)) return;

        const rewrite = directImports(ctx, specifier, barrel, imports);
        const barrelPath = relative(ctx.project.root, barrel);
        const range = ctx.range(node.source);
        ctx.report(
          diagnostics.VITE0023({
            why: `"${specifier}" resolves to the barrel file ${barrelPath}, which re-exports ${info.barrelModules.size} modules. In dev, Vite fetches and transforms every module the barrel re-exports even though this import only needs ${needed.size}.`,
            fix: `Import each binding from the module that defines it:\n${rewrite}`,
            sources: range ? [`${ctx.file.path}:${range.line}:${range.column}`] : undefined,
          }),
          {
            ruleId: "vite/imports/no-barrel-files",
            severity: ctx.severity,
            category: "imports",
            file: ctx.file.path,
            range,
            evidence: [
              {
                kind: "ast",
                file: barrel,
                summary: `Barrel file re-exports ${info.barrelModules.size} local modules and declares nothing itself.`,
              },
            ],
          },
        );
      },
    };
  },
});

function moduleInfo(ctx: RuleContext, file: string): ModuleInfo | null {
  const key = `vite:barrel-module:${file}`;
  const cached = ctx.cache.get<ModuleInfo | null>(key);
  if (cached !== undefined) return cached;
  const info = analyzeModule(ctx, file);
  ctx.cache.set(key, info);
  return info;
}

function analyzeModule(ctx: RuleContext, file: string): ModuleInfo | null {
  if (!SCRIPT_EXTENSIONS.includes(extname(file))) return null;
  const text = ctx.fs.readText(file);
  if (text === undefined) return null;
  const program = parseScript(file, text) as AnyNode;
  if (!program?.body) return null;

  const exports = new Map<string, Binding>();
  const stars: Array<string | null> = [];
  const imported = new Map<string, { from: string | null; name: string; type: boolean }>();
  const reexported = new Set<string>();
  const reexportedBindings = new Set<string>();
  let reexportOnly = !isGenerated(relative(ctx.project.root, file), text);
  const target = (source: AnyNode) =>
    typeof source?.value === "string" ? resolveSpecifier(ctx, file, source.value) : null;
  const reexport = (from: string | null, name: string, type: boolean): Binding => {
    if (!from) return { kind: "unknown" };
    if (!type) reexported.add(from);
    return { kind: "reexport", from, name, type };
  };

  for (const statement of program.body) {
    switch (statement.type) {
      case "ImportDeclaration": {
        const from = target(statement.source);
        if (statement.importKind !== "type" && !statement.specifiers?.length) reexportOnly = false;
        for (const item of statement.specifiers ?? []) {
          const name =
            item.type === "ImportDefaultSpecifier"
              ? "default"
              : item.type === "ImportNamespaceSpecifier"
                ? "*"
                : exportName(item.imported);
          if (name)
            imported.set(item.local.name, {
              from,
              name,
              type: statement.importKind === "type" || item.importKind === "type",
            });
        }
        break;
      }
      case "ExportAllDeclaration": {
        const from = target(statement.source);
        const type = statement.exportKind === "type";
        if (statement.exported) {
          const name = exportName(statement.exported);
          if (name) exports.set(name, reexport(from, "*", type));
        } else {
          stars.push(from);
          if (from && !type) reexported.add(from);
        }
        break;
      }
      case "ExportNamedDeclaration": {
        if (statement.declaration) {
          const type = isTypeDeclaration(statement.declaration);
          if (!type) reexportOnly = false;
          for (const name of declaredNames(statement.declaration))
            exports.set(name, { kind: "local", type });
          break;
        }
        const from = statement.source ? target(statement.source) : undefined;
        for (const item of statement.specifiers ?? []) {
          const exported = exportName(item.exported);
          const local = exportName(item.local);
          if (!exported || !local) continue;
          const type = statement.exportKind === "type" || item.exportKind === "type";
          if (from !== undefined) {
            exports.set(exported, reexport(from, local, type));
            continue;
          }
          const binding = imported.get(local);
          if (binding) {
            if (!type && !binding.type) reexportedBindings.add(local);
            exports.set(exported, reexport(binding.from, binding.name, type || binding.type));
          } else {
            exports.set(exported, { kind: "local", type });
            if (!type) reexportOnly = false;
          }
        }
        break;
      }
      case "ExportDefaultDeclaration": {
        const binding =
          statement.declaration?.type === "Identifier"
            ? imported.get(statement.declaration.name)
            : undefined;
        if (binding) {
          if (!binding.type) reexportedBindings.add(statement.declaration.name);
          exports.set("default", reexport(binding.from, binding.name, binding.type));
        } else {
          exports.set("default", { kind: "local", type: false });
          reexportOnly = false;
        }
        break;
      }
      case "TSInterfaceDeclaration":
      case "TSTypeAliasDeclaration":
      case "EmptyStatement":
        break;
      default:
        if (!(statement.type === "ExpressionStatement" && statement.directive))
          reexportOnly = false;
    }
  }

  for (const [name, binding] of imported) {
    if (!binding.type && !reexportedBindings.has(name)) reexportOnly = false;
  }

  return {
    reexportOnly,
    exports,
    stars,
    barrelModules: reexportOnly && reexported.size >= MIN_BARREL_MODULES ? reexported : null,
  };
}

function traceExport(
  ctx: RuleContext,
  file: string,
  name: string,
  depth: number,
  seen: Set<string>,
): Origin | null {
  const key = `${file}#${name}`;
  if (depth > MAX_TRACE_DEPTH || seen.has(key)) return null;
  seen.add(key);
  const info = moduleInfo(ctx, file);
  if (!info)
    return extname(file) === ".vue" && name === "default" ? { file, name, type: false } : null;
  const binding = info.exports.get(name);
  if (binding?.kind === "local") return { file, name, type: binding.type };
  if (!info.reexportOnly || binding?.kind === "unknown") return null;
  if (binding?.kind === "reexport") {
    if (binding.name === "*") return { file: binding.from, name: "*", type: binding.type };
    const origin = traceExport(ctx, binding.from, binding.name, depth + 1, seen);
    return origin && { ...origin, type: origin.type || binding.type };
  }
  if (name === "default") return null;
  const found: Origin[] = [];
  for (const star of info.stars) {
    if (!star) return null;
    const origin = traceExport(ctx, star, name, depth + 1, seen);
    if (origin) found.push(origin);
  }
  return found.length === 1 ? found[0]! : null;
}

function directImports(
  ctx: RuleContext,
  specifier: string,
  barrel: string,
  imports: Array<{ local: string; origin: Origin }>,
): string {
  const byFile = new Map<string, Array<{ local: string; origin: Origin }>>();
  for (const entry of imports)
    byFile.set(entry.origin.file, [...(byFile.get(entry.origin.file) ?? []), entry]);
  const lines: string[] = [];
  for (const [file, entries] of byFile) {
    const target = directSpecifier(ctx, specifier, barrel, file);
    const named: string[] = [];
    for (const { local, origin } of entries) {
      if (origin.name === "*") lines.push(`import * as ${local} from '${target}'`);
      else if (origin.name === "default") lines.push(`import ${local} from '${target}'`);
      else named.push(origin.name === local ? local : `${origin.name} as ${local}`);
    }
    if (named.length) lines.push(`import { ${named.join(", ")} } from '${target}'`);
  }
  return lines.join("\n");
}

function directSpecifier(
  ctx: RuleContext,
  specifier: string,
  barrel: string,
  file: string,
): string {
  const importer = ctx.file.path;
  const keepExtension = /\.[cm]?[jt]sx?$/.test(specifier);
  const strip = (path: string) => {
    if (extname(path) === ".vue") return path;
    if (keepExtension) return path.replace(/\.([cm]?)ts(x?)$/, ".$1js$2");
    return path.replace(/(?:\/index)?\.[cm]?[jt]sx?$/, "") || ".";
  };
  if (!specifier.startsWith(".")) {
    const base = /^index\.[cm]?[jt]sx?$/.test(basename(barrel))
      ? specifier.replace(/\/index(?:\.[cm]?[jt]sx?)?$/, "").replace(/\/$/, "")
      : dirname(specifier);
    const aliased = strip(join(base, relative(dirname(barrel), file)));
    if (resolveSpecifier(ctx, importer, aliased) === file) return aliased;
  }
  const path = strip(relative(dirname(importer), file));
  return path.startsWith(".") ? path : `./${path}`;
}

function resolveSpecifier(ctx: RuleContext, from: string, specifier: string): string | null {
  if (/[?#]/.test(specifier)) return null;
  const clean = specifier;
  const bases = /^\.\.?(?:\/|$)/.test(clean)
    ? [resolve(dirname(from), clean)]
    : aliasBases(ctx, clean);
  for (const base of bases) {
    const file = resolveFile(ctx, base);
    if (file && !GENERATED_PATH_RE.test(relative(ctx.project.root, file))) return file;
  }
  return null;
}

function resolveFile(ctx: RuleContext, base: string): string | null {
  const candidates = [base];
  const scriptExtension = /\.([cm]?)js(x?)$/.exec(base);
  if (scriptExtension)
    candidates.push(
      base.slice(0, scriptExtension.index) + `.${scriptExtension[1]}ts${scriptExtension[2]}`,
    );
  candidates.push(...RESOLVE_EXTENSIONS.map((extension) => `${base}${extension}`));
  candidates.push(...RESOLVE_EXTENSIONS.map((extension) => `${base}/index${extension}`));
  for (const candidate of candidates) {
    if (!RESOLVE_EXTENSIONS.includes(extname(candidate))) continue;
    if (ctx.fs.stat(candidate)?.isFile()) return candidate;
  }
  return null;
}

function aliasBases(ctx: RuleContext, specifier: string): string[] {
  const bases: string[] = [];
  for (const [pattern, targets] of tsconfigPaths(ctx)) {
    const star = pattern.indexOf("*");
    const prefix = star === -1 ? pattern : pattern.slice(0, star);
    const suffix = star === -1 ? "" : pattern.slice(star + 1);
    if (
      star === -1
        ? specifier !== pattern
        : !specifier.startsWith(prefix) || !specifier.endsWith(suffix)
    )
      continue;
    const captured =
      star === -1 ? "" : specifier.slice(prefix.length, specifier.length - suffix.length);
    bases.push(...targets.map((path) => path.replace("*", captured)));
  }
  if (bases.length) return bases;
  const alias = /^[@~]\/(.*)$/.exec(specifier);
  if (!alias) return [];
  return ["src", "app", ""].map((dir) => resolve(ctx.project.root, dir, alias[1]!));
}

function tsconfigPaths(ctx: RuleContext): Array<[string, string[]]> {
  const key = `vite:barrel-tsconfig-paths:${ctx.project.root}`;
  const cached = ctx.cache.get<Array<[string, string[]]>>(key);
  if (cached) return cached;
  const paths: Array<[string, string[]]> = [];
  for (const name of ["tsconfig.json", "tsconfig.app.json"]) {
    const file = resolve(ctx.project.root, name);
    if (!ctx.fs.stat(file)?.isFile()) continue;
    const config = ts.readConfigFile(file, (path) => ctx.fs.readText(path));
    if (config.error) continue;
    const parsed = ts.parseJsonConfigFileContent(config.config, configHost(ctx), ctx.project.root);
    const options = parsed.options as ts.CompilerOptions & { pathsBasePath?: string };
    const base = options.baseUrl ?? options.pathsBasePath ?? ctx.project.root;
    for (const [pattern, targets] of Object.entries(options.paths ?? {}))
      paths.push([pattern, targets.map((path) => resolve(base, path))]);
  }
  ctx.cache.set(key, paths);
  return paths;
}

// Only compiler options are read, so the host never lists directories for `include` patterns.
function configHost(ctx: RuleContext): ts.ParseConfigHost {
  return {
    useCaseSensitiveFileNames: true,
    readDirectory: () => [],
    fileExists: (path) => ctx.fs.stat(path)?.isFile() ?? false,
    readFile: (path) => ctx.fs.readText(path),
  };
}

function isPackageEntry(ctx: RuleContext, file: string): boolean {
  let dir = dirname(file);
  const root = resolve(ctx.project.root);
  while (dir.startsWith(root)) {
    const manifestPath = join(dir, "package.json");
    if (ctx.fs.stat(manifestPath)?.isFile()) {
      const manifest = ctx.fs.readJson(manifestPath);
      if (!isRecord(manifest)) return false;
      const entries = packageEntryTargets(manifest);
      return entries.some((entry) => {
        if (!entry.target) return false;
        for (const candidate of entrySourceCandidates(dir, entry.target)) {
          const match = matchesEntry(candidate, file, entry.pattern);
          if (!match.matched) continue;
          if (entry.key) {
            const concreteKey = entry.key.replaceAll("*", match.subpath);
            const selected = entries
              .filter((item) => item.key && matchesSubpath(item.key, concreteKey))
              .sort((a, b) => compareExportKeys(a.key!, b.key!))[0];
            if (selected?.key !== entry.key) continue;
          }
          return true;
        }
        return false;
      });
    }
    if (dir === root) break;
    dir = dirname(dir);
  }
  return false;
}

function packageEntryTargets(
  manifest: Record<string, unknown>,
): Array<{ key: string | null; target: string | null; pattern: boolean }> {
  const targets: Array<{ key: string | null; target: string | null; pattern: boolean }> = [];
  const collect = (value: unknown, key: string | null, pattern: boolean) => {
    if (typeof value === "string" || value === null)
      targets.push({ key, target: typeof value === "string" ? value : null, pattern });
    else if (Array.isArray(value)) {
      for (const item of value) {
        const before = targets.length;
        collect(item, key, pattern);
        if (targets.slice(before).some((entry) => entry.target !== null)) break;
      }
    } else if (value && typeof value === "object") {
      for (const [condition, target] of Object.entries(value)) {
        collect(target, key, pattern);
        if (condition === "default") break;
      }
    }
  };
  const exports = manifest.exports;
  if (exports != null) {
    if (
      typeof exports === "object" &&
      !Array.isArray(exports) &&
      Object.keys(exports).some((key) => key.startsWith("."))
    ) {
      for (const [key, target] of Object.entries(exports)) {
        const before = targets.length;
        collect(target, key, key.split("*").length === 2);
        if (targets.length === before)
          targets.push({ key, target: null, pattern: key.split("*").length === 2 });
      }
    } else collect(exports, ".", false);
  } else {
    collect(manifest.main, null, false);
    collect(manifest.module, null, false);
  }
  return targets;
}

function matchesEntry(
  candidate: string,
  file: string,
  pattern: boolean,
): { matched: boolean; subpath: string } {
  if (!pattern || !candidate.includes("*")) return { matched: candidate === file, subpath: "" };
  const parts = candidate.split("*").map((part) => part.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"));
  const expression = parts.shift()! + "(?<subpath>.+)" + parts.join("\\k<subpath>");
  const match = new RegExp(`^${expression}$`).exec(file);
  return { matched: Boolean(match), subpath: match?.groups?.subpath ?? "" };
}

function compareExportKeys(a: string, b: string): number {
  const aStar = a.indexOf("*");
  const bStar = b.indexOf("*");
  if (aStar === -1) return bStar === -1 ? 0 : -1;
  if (bStar === -1) return 1;
  return bStar - aStar || b.length - a.length;
}

function matchesSubpath(pattern: string, subpath: string): boolean {
  const expression = pattern
    .split("*")
    .map((part) => part.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"))
    .join(".*");
  return new RegExp(`^${expression}$`).test(subpath);
}

function entrySourceCandidates(dir: string, target: string): string[] {
  const path = resolve(dir, target);
  const stem = path.replace(/\.(?:d\.)?[cm]?[jt]sx?$/, "");
  const sourceStem = resolve(
    dir,
    relative(dir, stem).replace(/^(?:dist|lib|build|out|esm|cjs|es)(?=\/)/, "src"),
  );
  return [
    path,
    ...[stem, sourceStem].flatMap((base) => SCRIPT_EXTENSIONS.map((ext) => base + ext)),
  ];
}

function isGenerated(relativePath: string, text: string): boolean {
  return (
    GENERATED_PATH_RE.test(relativePath) ||
    GENERATED_FILE_RE.test(relativePath) ||
    GENERATED_HEADER_RE.test(text.slice(0, 300))
  );
}

function isTypeDeclaration(node: AnyNode): boolean {
  return (
    node.type === "TSInterfaceDeclaration" ||
    node.type === "TSTypeAliasDeclaration" ||
    node.declare === true
  );
}

function declaredNames(node: AnyNode): string[] {
  if (node.type === "VariableDeclaration")
    return node.declarations.flatMap((declaration: AnyNode) => patternNames(declaration.id));
  return node.id?.name ? [node.id.name] : [];
}

function patternNames(node: AnyNode): string[] {
  if (!node) return [];
  if (node.type === "Identifier") return [node.name];
  if (node.type === "ObjectPattern")
    return node.properties.flatMap((property: AnyNode) =>
      patternNames(property.type === "RestElement" ? property.argument : property.value),
    );
  if (node.type === "ArrayPattern") return node.elements.flatMap(patternNames);
  if (node.type === "AssignmentPattern") return patternNames(node.left);
  if (node.type === "RestElement") return patternNames(node.argument);
  return [];
}

function exportName(node: AnyNode): string | null {
  if (!node) return null;
  if (node.type === "Identifier") return node.name;
  return typeof node.value === "string" ? node.value : null;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}
