name: Release

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  publish-alpha:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          registry-url: https://registry.npmjs.org
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm release:check
      - run: pnpm release:version
      - run: pnpm release:pack
      - run: pnpm release:publish:alpha
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
